language: node_js

node_js:
  - "node"

cache:
  directories:
    - node_modules

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: pages
  committer_from_gh: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
